### ISSUE TITLE
Is it really a good idea to invent a fake fetch() method when a real fetch() method exists already in browsers?

### ISSUE THREAD

**Issue by onlywei** [button/codelab-async-js#1]
> Suppose that we have a method fetch() that does GET requests and has an interface...

The real `fetch()` has a different API than what you've used in this code lab 😝

**Comment by mightyguava** [comment]
`fetch()` renamed to `fetchJson()` https://github.com/button/codelab-async-js/commit/86ae8475feaf2d03d27c5ec6969f2d9051df19bb
